repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.5.2
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        # language_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0  # Use the ref you want to point at
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
